Add files via upload
Microsoft Windows [Version 10.0.22631.5039]
(c) Microsoft Corporation. All rights reserved.

C:\Users\asrae>cd ..

C:\Users>cd ..

C:\>cd 'ENSF 400'
The system cannot find the path specified.

C:\>cd "ENSF 400"

C:\ENSF 400>cd "Sonar"

C:\ENSF 400\Sonar>cd "sonarqube-25.4.0.105899"

C:\ENSF 400\Sonar\sonarqube-25.4.0.105899>cd "sonarqube-25.4.0.105899"

C:\ENSF 400\Sonar\sonarqube-25.4.0.105899\sonarqube-25.4.0.105899>cd "bin"

C:\ENSF 400\Sonar\sonarqube-25.4.0.105899\sonarqube-25.4.0.105899\bin>ls
'ls' is not recognized as an internal or external command,
operable program or batch file.

C:\ENSF 400\Sonar\sonarqube-25.4.0.105899\sonarqube-25.4.0.105899\bin>cd "windows-x86-64"

C:\ENSF 400\Sonar\sonarqube-25.4.0.105899\sonarqube-25.4.0.105899\bin\windows-x86-64>StartSonar.bat
Starting SonarQube...
Error: LinkageError occurred while loading main class org.sonar.application.App
        java.lang.UnsupportedClassVersionError: org/sonar/application/App has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

C:\ENSF 400\Sonar\sonarqube-25.4.0.105899\sonarqube-25.4.0.105899\bin\windows-x86-64>set JAVA_HOME="C:\Program Files\Java 17"

C:\ENSF 400\Sonar\sonarqube-25.4.0.105899\sonarqube-25.4.0.105899\bin\windows-x86-64>set PATH=%JAVA_HOME%\bin;%PATH%

C:\ENSF 400\Sonar\sonarqube-25.4.0.105899\sonarqube-25.4.0.105899\bin\windows-x86-64>StartSonar.bat
Starting SonarQube...
2025.04.13 04:39:40 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory C:\ENSF 400\Sonar\sonarqube-25.4.0.105899\sonarqube-25.4.0.105899\temp
2025.04.13 04:39:40 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on [HTTP: 127.0.0.1:9001, TCP: 127.0.0.1:{}]
2025.04.13 04:39:40 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[ELASTICSEARCH] from [C:\ENSF 400\Sonar\sonarqube-25.4.0.105899\sonarqube-25.4.0.105899\elasticsearch]: C:\Program Files\Java 17\bin\java -Xms4m -Xmx64m -XX:+UseSerialGC -Dcli.name=server -Dcli.script=./bin/elasticsearch -Dcli.libs=lib/tools/server-cli -Des.path.home=C:\ENSF 400\Sonar\sonarqube-25.4.0.105899\sonarqube-25.4.0.105899\elasticsearch -Des.path.conf=C:\ENSF 400\Sonar\sonarqube-25.4.0.105899\sonarqube-25.4.0.105899\temp\conf\es -Des.distribution.type=tar -cp C:\ENSF 400\Sonar\sonarqube-25.4.0.105899\sonarqube-25.4.0.105899\elasticsearch\lib\*;C:\ENSF 400\Sonar\sonarqube-25.4.0.105899\sonarqube-25.4.0.105899\elasticsearch\lib\cli-launcher\* org.elasticsearch.launcher.CliToolLauncher
2025.04.13 04:39:40 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
2025.04.13 04:39:54 INFO  app[][o.s.a.SchedulerImpl] Process[es] is up
2025.04.13 04:39:54 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[WEB_SERVER] from [C:\ENSF 400\Sonar\sonarqube-25.4.0.105899\sonarqube-25.4.0.105899]: C:\Program Files\Java 17\bin\java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=C:\ENSF 400\Sonar\sonarqube-25.4.0.105899\sonarqube-25.4.0.105899\temp -XX:-OmitStackTraceInFastThrow --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Dhttp.nonProxyHosts=localhost|127.*|[::1] -cp ./lib/sonar-application-25.4.0.105899.jar;C:\ENSF 400\Sonar\sonarqube-25.4.0.105899\sonarqube-25.4.0.105899\lib\jdbc\h2\h2-2.3.232.jar org.sonar.server.app.WebServer C:\ENSF 400\Sonar\sonarqube-25.4.0.105899\sonarqube-25.4.0.105899\temp\sq-process1606760611651965864properties
Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
2025.04.13 04:40:32 INFO  app[][o.s.a.SchedulerImpl] Process[web] is up
2025.04.13 04:40:32 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[COMPUTE_ENGINE] from [C:\ENSF 400\Sonar\sonarqube-25.4.0.105899\sonarqube-25.4.0.105899]: C:\Program Files\Java 17\bin\java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=C:\ENSF 400\Sonar\sonarqube-25.4.0.105899\sonarqube-25.4.0.105899\temp -XX:-OmitStackTraceInFastThrow --add-opens=java.base/java.util=ALL-UNNAMED --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Dhttp.nonProxyHosts=localhost|127.*|[::1] -cp ./lib/sonar-application-25.4.0.105899.jar;C:\ENSF 400\Sonar\sonarqube-25.4.0.105899\sonarqube-25.4.0.105899\lib\jdbc\h2\h2-2.3.232.jar org.sonar.ce.app.CeServer C:\ENSF 400\Sonar\sonarqube-25.4.0.105899\sonarqube-25.4.0.105899\temp\sq-process11472707816221051394properties
2025.04.13 04:40:32 WARN  app[][startup] ####################################################################################################################
2025.04.13 04:40:32 WARN  app[][startup] Default Administrator credentials are still being used. Make sure to change the password or deactivate the account.
2025.04.13 04:40:32 WARN  app[][startup] ####################################################################################################################
Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
2025.04.13 04:40:35 INFO  app[][o.s.a.SchedulerImpl] Process[ce] is up
2025.04.13 04:40:35 INFO  app[][o.s.a.SchedulerImpl] SonarQube is operational